/* tslint:disable */
export const text = `   Le projet de 14000m2 articule trois échelles: le campus, la résidence et le logement. Il ambitionne de créer un lieu de vie actif et généreux.
   Deux ensembles bâtis dégagent un parc, ouvert sur le quartier, qui rassemble les résidences (1000 logements).
   L'architecture sobre du projet laisse délibérément la place aux appropriations en développant des espaces potentiels.À la forme primitive des volumes en cloître répond l’abstraction du panneau tout à la fois volet et parement de façade. Sa mesure cadence tout le projet, modifie la perception de l’échelle et dilue l’effet de ruche que pourrait provoquer la répétition et l’empilement des 615 logements. Toujours changeant, cet épiderme réagit autant à son milieu par ses reflets qu’aux pratiques de ses occupants par sa mobilité.Les abords du site se caractérisent par un tissu résidentiel constitué d’ensembles individuels et de quelques bâtiments collectifs. Un travail d'évidements et de cadencement du bâti dans le projet vient faire écho à cette diversité morphologique identitaire du quartier.Un grande vide est aménagé entre les deux bâtiments. Il laisse à voir le cœur d'îlot depuis la rue. Celui-ci vient s'ajouter à la diversité de paysages issus de l'échelle individuelle qui fabriquent l'image collective de la Côte Pavée.Le projet adopte une écriture architecturale qui s’inscrit dans une époque et un contexte tout en restituant un caractère institutionnel et intemporel au siège social. L’image actuelle d’une tour posée sur un socle est entièrement repensée pour la lecture d’un unique bâtiment contemporain et repérable.Le patio propose une continuité intérieur/extérieur, qui prolonge la place du village sur l’extérieur. Ce jardin a les qualités d’agrément d’un espace extérieur planté et devient un espace de centralité qui intègre les bâtiments annexes situés rue Saint-Lazare. Ces constructions sont désormais reliées au siège et accueillent des activités complémentaires.Une façade ventilée compose l’enveloppe générale du siège social. L’ensemble est homogène, et l’aspect immatériel donné par le mur rideau respirant change totalement l’image du bâtiment actuel.L'hôtel s'installe dans un contexte fragile abritant deux espaces boisés classés et d'anciens corps de fermes. L'ensemble du projet est dirigé par une recherche de rapport sensible à ce paysage. L’alignement aux bâtiments esquisse une grande allée qui fédère l'ensemble et redonne vie au site.Le bâtiment s'exprime comme un volume souple épousant le paysage pour préserver le charme singulier du lieu. Cette implantation permet de supprimer les vis-à-vis entre les chambres qui profitent de vues privilégiées sur le parc et sa végétation abondante.La répétition de la fenêtre dessine une façade épurée. Cette simplicité est habillée par la silhouette des arbres qui se reflètent dans les panneaux d'Alucobon.Entre Garonne et canaux, un parc habité pour préserver la situation unique des Amidonniers, village enclavé par les infrastructures de la métropole.
   Un grand sol partagé accueille des usages pour le quartier. Les bassins des filtres conservent leur caractère de jardin secret dans la ville.Dans les plots qui parsèment le parc, on habite entre le bosquet, les bassins et la Garonne. Les appartements sont doubles orientés. Leurs espaces de vie et les chambres s'ouvrent tous sur de vastes terrasses. Aux beaux jours, les logements voient ainsi leur surface augmenter de 30 à 40%Un piétonnier urbain préserve le site des nuisances de la métropole.  Un grand sol public ponctué d'évènements de paysage se déploie dans l'ensemble du bois habité. Il se prolonge dans les rez-de-chaussée qui accueillent un ensemble de locaux dédiés aux associations et à la collectivité.Un ensemble bâti urbain fabrique la transition entre l'échelle de la métropole et les Amidonniers le long de la rocade. Cet élément gère les nuisances acoustiques et aériennes pour l'ensemble du quartier, concentre le stationnement et accueille un ensemble d'usages variés. Une infrastructure paysage pour densifier sans étouffer le site qui par sa stature offre un nouveau signal à l'entrée de la ville.Le nouvel espace Croix-Baragnon pose trois enjeux. Attirer le public vers sa cour intérieure, faire cohabiter les différentes institutions qu'il accueille et développer un centre culturel à l'échelle métropolitaine.Le projet ouvre le rez-de-chaussée, de la rue à la cour, afin d'en faire une destination et une étape indispensable pour le public sur cette rue passante. Le CROA et ses satellites, la MA, le CAUE et le groupe Carle partagent des espaces. Entre lieu de travail qui reçoit et lieu public, l'espace partagé promeut.L’ilôt donne une expression forte de la ville comme espace public.
   Sur la place basse, les bâtiments ne sont pas mitoyens. Ils sont
   autonomes et laissent passer la lumière du sud au dessus
   des commerces et répondent à la dynamique verticale  
   de l’existant.Ils sont pourtant assemblés par leur répétition,
   leur matériau et leur alignement. En haut, face au bâtiment
   patrimonial des associations, les volumes s’alignent et fabriquent
   un lieu identitaire apaisé pour le quartier Garonne-Saint Agne.
   L’ilôt n’est pas fermé, les vues le traversent de part en part.
   A chacun de ses angles, des éléments dialoguent avec
   le contexte. Les programmes libres et sociaux fabriquent ensemble
   ce morceau de ville autour d’un grand jardin qui évoluera avec ses
   habitants. Tous les logements disposent de vues lointaines.Le bâtiment se situe au centre de l'OAP des Arènes. Par sa forme particulière en Z, le bâtiment se tourne à la fois vers le Cristal (bâtiment des années 60) et vers le coeur d'îlot créé dans le cadre de l'OAP des Arènes. Le bâtiment invite l'habitant ou le visiteur à tourner autour, et joue un rôle majeur dans le quartier en favorisant la porosité de ce dernier. La programmation de maison de quartier située au rez-de-chaussée du projet permet de dynamiser l'espace public qui l'entoure et devient un bâtiment central pour les habitants du quartier, non seulement pour sa position au coeur de l'OAP mais également pour sa programmation.
   Sa volumétrie en gradins et sa forme particulière en Z permet au bâtiment de rompre avec la trame orthogonale du quartier et de s'y intégrer grâce à la gradation des hauteurs (du R+3 au R+9).A Empalot, l'architecture est le lien entre l'intimité du logement et le vivre ensemble des déambulations urbaines.
   Le TR8 parie sur l'intensité des usages en rez-de-chaussée et une écriture rationnelles dans les étages de logements.Les rez-de-chaussée sont généreusement ouverts. Dans le prolongement de l’espace public, une grande cour plantée supporte les deux bâtiments. Leur structure se déploie vers l’extérieur pour aménager un ensemble de dispositifs capables d’accueillir tout type d’usages.Dans chaque appartement, les loggias sont des pièces extérieures qui étendent la surface du logement aux beaux jours. Dans un quartier historiquement marqué par une architecture du chemin de grue, elles offrent des vues lointaines vers le grand paysage.De la rue à l'appartement, on traverse une succession d'espaces aménagés au service de la collectivité. Le porche, la cour, les rez-de-chaussée et les paliers sont autant d'endroits d'interactions pour les habitants.Un centre sportif au milieu des champs et des terrains de jeux. Une forme simple lisible et compréhensible immédiatement.La forme simple, insécable, concentre l'attention sur les interactions rendues possibles plutôt que sur la complexité technique qu'elle peut receler.
   Selon cette logique, le terrain principal s'inscrit dans le sol pour que l'ensemble n'impacte pas le paysage.
   Le bâtiment entretient un rapport sensible au paysage.Sous une même structure, deux grandes entités: une cuve avec les terrains principaux et un vide réceptacle. Ce vide est un espace neutre rempli d'histoires possibles. La décision radicale de la toiture et de ses grands franchissements dégage ces opportunités. Les usagers pourront reprogrammer le bâtiment au besoin.Le bâtiment définit un cœur d’îlot pour les habitants. L’aile Est du projet transcrit la volonté de conforter la place centrale et l’axe urbain de la ZAC. Deux volumétries affirmées abritent logements aux étages et parking et services au rez-de-chaussée. L’aile Ouest, plus découpée développe une architecture semi-urbaine, attentive à ses voisins, dont les proportions dialoguent avec les pavillons aux alentours.Du fait du caractère inondable de la ZAC Piquepeyre, les 43 logements sont répartis sur un nouveau niveau de référence au premier étage en périphérie de la parcelle. Cette implantation permet la création d’un parc collectif, véritable jardin d’Eden. C’est une promenade rythmée de surprises au détour de bosquets ondulants : un jardin potager de 200m2, des arbres fruitiers et des refuges de biodiversité disséminés, une placette bordée de baies fruitières, une prairie ouverte.Ce petit bâtiment de laboratoires est le nouveau porte-drapeau d'un grand campus de recherche. Il marque l'entrée du site. Les champs environnants sont le terrain de jeu des chercheurs.Le bâtiment, très léger, se glisse entre les arbres existant. Il reflète son environnement. Son apparence change au fil des saisons.Le bâtiment peut être modifié: les outils et les méthodes de l'INRA évoluent constamment. Les éléments techniques nombreux, ne conditionnent pas la répartition fonctionnelle des espaces.Les façades sont préfabriquées dans les ateliers d'un charpentier. Les grands panneaux verticaux ralentissent le regard. Leurs montants métalliques reflètent l'environnement. La toile qui remplit les cadres de métal vibre sous le vent.Le projet concerne la réhabilitation et l'extension d'une maison d'époque à Lardenne.
   L'extension au rez-de-chaussée s'implante dans la logique d'agrandissement de la maison, en retrait par rapport à l'existant et se développant sur le jardin.
   La nouvelle construction sera édifiée sur un socle de béton brut construit en continuité du socle en pierre de la maison existante. Ce dernier permettra  de relier les deux ensembles. L'extension, en structure légère  métallique posée sur ce socle en béton, reprendra le rythme vertical des façade de la maison existante réinterprétée de manière contemporaine et épurée. Des panneaux de remplissage opaques, ajourés ou transparents permettront de révéler l'usage intérieur du bâtiment (cuisine ou salle de restauration) ou de créer un tableau abstrait reflétant la végétation luxuriante qui entoure la maison.Le projet adopte caractère métropolitain et densité. Depuis la promenade plantée le regard file vers le jardin au travers du dispositif topographique et paysagé sans être arrêté. Le jardin offre un paysage intérieur ouvert sur le coeur de la ZAC, à l’échelle des bâtiments qui l’entourent.Toulouse est une métropole verte, exemple de densité maîtrisée et de qualité de vie en Europe.
   Le jardin offre un paysage intérieur ouvert sur le cœur de la ZAC, à l’échelle des bâtiments voisins. Ce paysage dissimule l’étendue de parking du Zénith. De l’autre, il crée une limite topographique, paysagère et poreuse sur le coeur traversant de la ZAC : la promenade jardinée.Les espaces extérieurs privatifs sont valorisés. Pensés comme de véritables pièces supplémentaires des logements. Ce sont des lieux de convivialité pensés pour préserver les habitants des vis à vis.L'ordonnancement des volumes et des façades indiquent autant la destination que le contenu du bâtiment.  Ses strates résonnent avec celles du temps et de notre mémoire.
   Le bâtiment compact, sans ouverture, isole les ouvrages de l'extérieur.De loin, la masse et la matière se confondent. Elles font signe dans une zone périphérique qui accueille à la fois logements et entrepôts.La maison de retraite se glisse dans un parc classé. De grandes vitrines instaurent une relation forte entre chaque résident et le monde au dehors. Ces fenêtres habitées constituent le visage de la forme bâtie. Leur répétition donne à voir la singularité de chaque résident.Le bâtiment slalome entre les arbres. La fenêtre définit le rapport au paysage. Avec la dépendance, lumière naturelle et cycles naturels définissent les repères principauxLe sol comme continuité de l’espace public.
   Un cadencement des masses bâties qualifie le vide, libère le regard et les accès au coeur d’îlot.
   Le vide est traversé, ou regardé.Bâti et paysage sont pensés de concert, comme le socle commun du projet.
   La topographie et les plantations sont une continuité et une complémentarité de l’espace bâti.
   Le rez-de-chaussée libéré de logements permet la gestion des stationnements et des espaces communs et partagés.Chaque appartement possède un paysage différent suivant les vues, les étages et les orientations.
   Pour chaque logement, des loggias et balcons sont une véritable pièce en plus.
   Un jeu de déformation des masses des balcons et séjours oriente le regard vers la plus grande percée visuelle et gère le vis-à-vis.
   La majorité les logements sont doubles ou triples orientés.Une lecture de bas vers le haut est introduite par la présence de larges bandeaux horizontaux qui rythment la façade.
   Le jeu de cadencement de la masse dans l’implantation des bâtiments se retrouve dans le travail d’épaisseur de la façade. Un jeu de matière travaillée en relief.L'intermédiaire permet une densité  cohérente entre tissu pavillonnaire et évolution du quartier. Une successions de cours partagées organisent le projet et fabrique l'intimité des logements.
   Il ne s'agit pas de vivre dans une opération de 160 logements mais dans 10 opérations de 16 logements.Les cours accueillent les usages communs du quotidien. Elles se prolongent et s'élargissent pour créer des placettes qui offrent partage et convivialité à l'échelle du quartier. Elles sont des respirations et des pôles d'usages attractifs pour les habitants et les riverains.Andromède est un parc habité. L'îlot 19B est traité comme un ensemble s'adressant à cette identité forte du quartier.
   Le projet dégage un cœur d'îlot qui prolonge la structure de la ZAC. L'ensemble des cinq plots s'ouvrent généreusement sur ce paysage.L'ensemble des appartements sont double orientés. Les terrasses sont l'espace intermédiaire entre le parc urbain et l'intimité du logements. La trame de façade  offre de grands cadrages sur le bosquet et le jardin depuis toutes les pièces de vie.Le projet signale la place des Halles du quartier.
   Les gabarits bâtis répondent aux alentours et laissent filer le regard. Le rez-de-chaussée entre en résonance avec les Halles, le marché et l'îlot ouest à venir autour de la place. L'échelle fabrique la place.L'ensemble des appartements sont double orientés et disposent de vastes espaces extérieurs.
   Les façades varient pour s'adapter aux différents usages et assurer l'intimité des logements. Leur opacité diminue en s'élevant vers le ciel.Le sol comme continuité de l’espace public.
   Un cadencement des masses bâties qualifie le vide, libère le regard et les accès au coeur d’îlot.
   Le vide est traversé, ou regardé.Le jardin, s’ouvrir sur la végétation.
   Placer les arbres depuis les appartements, chaque appartement possède un paysage différent suivant les vues et les étages.L’opération prévoit la construction de deux bâtiments : le premier situé au sud de la parcelle en forme de U rassemblera les 90 logements collectifs, le second situé au nord de la parcelle rassemblera les 27 logements intermédiaires.
   Le projet propose la lecture de deux bâtiments très largement découpés, rapellant la caractère du faubourg recherché dans le projet. Le projet cherche à mettre en relation les échelles domestiques et collectives. Ces deux échelles s’expriment dans la mise en oeuvre des matériaux et les dispositifs d’espaces extérieurs mis en place. Des bandeaux horizontaux permettent de relier les différentes altimétries des bâtiments et relient l’échelle des logements intermédiaires avec celle des logements collectifs. Les loggias situées dans les angles et leurs superpositions à tous les niveaux permettent de créer des lignes verticales en façade et de jouer entre verticalité et horizontalité/ pleins et vides.On rentre chez-soi par une courette comme dans un pavillon. Les appartements sont traversants, distribuant lumière et ventilation naturelle. Les grands balcons permettent mille appropriation possibles. Sur les terrasses, une mise en œuvre sophistiquée donne une préciosité à ce qui serait une simple boîte enduite.Les coursives surdimensionnées deviennent des espaces de rencontre communs aux vingt familles. Les entrées indépendantes laissent de grandes libertés aménagement.Au sud, une grande pièce entre le soleil et l'intérieur des logements. Grâce aux dispositifs d'occultations, les grandes terrasses peuvent s'ouvrir sur la rue ou devenir des pièces extérieures intimes.Les bâtiments sont implantés en périphérie de la parcelle dégageant ainsi un coeur d’ilôt généreux offrant des porosités visuelles pour le quartier. Un grand jardin partagé à destination des habitants y est aménagé.Les bâtiments sont séquencés par des circulations extérieures qui ouvrent des perspectives sur le coeur d'îlot et les environs. Ils se déforment en vue d'offrir à chaque typologie d'appartement un espace extérieur conséquent. Les derniers niveaux bénéficient quant à eux de grands jardins privatifs, aménagés en toiture.Le projet s'inscrit dans le quartier Chalets, entre animation d'une rue très passante et grands jardins en cœur d'îlot. Rue Roquelaine, le bâtiment prend place dans une séquence d'architectures du XIXème siècle. Le dessin d'une double façade permet d'habiter des espaces extérieurs sur rue.Ces logements contemporains se glissent dans le tissu bourgeois du centre toulousain. La sophistication de la façade renvoie aux avoisinants dessinés par les modénatures.Le cœur d'îlot est le jardin de la résidence. Il est une respiration dans ce quartier très minéral. Tournées vers cet espace, de grandes terrasses pour se projeter dans le paysage.L'enjeu de l'opération réside dans l'implantation d'un programme de logement collectif au sein d'un contexte largement caractérisé par l'habitat individuel. Chaque composante du projet est envisagée par le prisme des codes de l'habitat individuel local, afin d'intégrer ce contexte si spécifique.Le collège est situé dans un paysage naturel fait de champs en jachère, de bois et de lacs. Il est proche d'une petite ville.
   C'est une architecture non figurative. Le bâtiment est une frontière qui définit des espaces extérieurs: entrée, sports, cour de récréation, livraisons. La forme construite résulte des besoins des utilisateurs.Faites de bois et de verre, les façades s'accordent aux orientations et aux besoins intérieurs. C'est un objet caméléon, faits de matériaux de son lieu. Il en reflète les aspects les plus remarquables.Le projet est un signal urbain. L’empilement de grands jardins d’hiver et terrasses au sud, visible de loin, s’adresse aux Allées Jaurès, à la médiathèque José Cabanis et au Canal. C’est un objet en dialogue avec le contexte : par sa hauteur, finalement proche des immeubles voisins, par l’extension de son rez-de-chaussée vers l’espace public.Le bâtiment est un objet urbain mystérieux : son architecture unitaire cache sa diversité intérieure. Par sa mixité programmatique, il peut devenir une nouvelle référence de la vie «métropolitaine» à Toulouse.Le groupe scolaire respecte l'équilibre du paysage existant. Dans sa morphologie, le bâtiment dialogue avec les voisins proches du quartier en assurant une continuité visuelle des espaces verts. Les espaces extérieurs à l'échelle du quartier ont capacité à former de grands espaces publics pour la ville.A la manière des écoles communales, un parvis s'ouvre sur le quartier. Il accueille les usages quotidiens des famille ou des évènements citoyens ponctuels: attente apaisée le matin et le soir, activité sportive, kermesses...Les espaces de rencontre sont nombreux. Ils permettent d'apprendre à vivre ensemble et à apprendre en groupe.Les patios sont des lieux d'éveil aux sens. Ils permettent aux enseignants la transmission des repères et des connaissances avec d'autres dispositifs que celui de la classe. Ces espaces, ponctués de différents jardins sont le paysage apaisé partagé par les salles de classe.L'espace "Partageons +" est conçu comme un outil au service de la collectivité au plus proche de l'usager et du grand public. Le contenu mis à disposition dans ce centre de ressources vise à encourager les comportements éco-citoyens en participant à la sensibilisation aux enjeux de l'eau.L’îlot N participe à la création d’une nouvelle entrée pour Pibrac
   Le projet propose un modèle de développement contemporain adoptant une démarche environnementale responsable qui met à profit les gisements disponibles sur site tels que les apports solaires et les vents dominants.L'implantation en lanières libèrent de grandes bandes paysagées entre les ensembles de logements. Dans le prolongement des jardins privatifs, des espaces au service de la collectivité ont capacité à accueillir les usages communs.Les maisons de plain pied  disposent de grands jardins au rez-de-chaussée. On rentre chez-soi par cet espace extérieur. Les séjours sont orientés sud.
   Dans les logements intermédiaires, deux appartements partagent un palier intime. De grandes terrasses au sud étendent le salon aux beaux jours.L’enjeu est de faire signe en fabriquant un marqueur culturel du
   territoire.
   Mettre en place dans trois contextes différents, un signe
   partageable par tous.L’enjeu est de faire signe en fabriquant un marqueur culturel du
   territoire.
   Mettre en place dans trois contextes différents, un signe
   partageable par tous.L'Espace Andromède, au cœur du futur quartier réunit trois objectifs. Expliquer le projet de façon intelligible à travers une maquette, offrir un panorama sur le quartier en évolution et abriter les bulles de promotion.
   Une tour fait signal dans le paysage. A sa base, la maquette, au sommet, une vue sur la construction de la ZAC.
   A la demande des habitants, ce bâtiment à vocation temporaire se pérennise pour devenir un centre communautaire.Le CIAP participe à la réactivation du centre-bourg. Le parvis et le toit du bâtiment recréent des espaces publics pour le village.
   Le bâtiment permet de retrouver un point de vue sur la vallée.La Maison du Gouverneur est un collage d'époques. Le projet les dévoilent en dégageant un grand vide vertical. Les mezzanines offrent des points de vue inédits au cœur de la Maison.
   Le CIAP et son café participent à la vie quotidienne du village.Neuchâtel est une ville dans la pente, cernée d'un côté par la forêt, de l'autre par un lac. Le projet agit par acupuncture.
   On couvre la voie qui séparait la ville haute et la ville basse. On intensifie les potentiels existants. Du tertiaire, de l'universitaire et des loisirs s'installent le long du lac.
   Des services sur les voies. Des logements en bordure de forêt.Le projet complète un collège datant des années 1960. La cour carrée organise la vie du nouveau collège. Le noir parle de lumière et permet le mariage de l'ancien et du neuf.Stratégies d'intervention sur trois îlots représentatifs des tissus toulousains, analysés selon des critères qui nous servent de base à la réflexion de projets insérés dans ces tissus.A Haïti, il y a une tradition de messes publiques. Après le séisme de 2010 elles sont devenues une forme de reconstruction collective. La forme pose les célébrants au même degré en rapport immédiat avec le ciel. Une esthétique de l'expérience. La forme simple simple n'a pas besoin d'être figurative ou symbolique.Le projet est une maison mur qui fonctionne sur elle-même comme une forteresse se protégeant de l'environnement et préservant l'intimité de ses usagers. A l'extérieur, la maison résonne avec son environnement. Le toit offre une vue panoramique sans barrière visuelle, sa masse la met en tension avec le voisinage. Son antre est partagé entre l'ouverture et la protection de soi.Le projet s'adresse au grand territoire. Il signale Borderouge depuis la rocade. Du jardin jusqu'au toit, paysage et plateaux dialoguent par glissement de l'un à l'autre en effaçant leurs frontières respectives.Ouvert sur le boulevard urbain, Rhizom rayonne dès l’arrivée du périphérique.
   Ses volumes protègent les occupants et les jardins de l’agitation de la rocade.De larges balcons habités voyagent le long des façades.
   Chacun peut profiter des îlots de fraîcheur ménagés par les jardins en travaillant.
   Véritables laboratoires des usages, ces espaces extérieurs protégés des intempéries et du vent profitent d’une vue magnifique.La typologie intermédiaire permet la cohabitation. La succession des toitures individuelles dessine la silhouette du projet. Le découpage des volumes recrée des sous-échelles, dans les gabarits du bâti environnant. La zone protégée est le jardin partagé des habitants.La mitoyenneté et les accès individualisés créent des interactions. A l’Est, les logements sont desservis par les jardins, depuis une venelle piétonne.Vivre dans les Monges, c'est évoluer entre plaine et forêt au pied de Cornebarrieu. Les villas urbaines de l'îlot N1 sont disposées dans un grand jardin. Celui-ci est posé comme opportunité d'imaginaires, une manière de "prendre l'air", comme on prend une pause.L'intérieur de l'îlot est un généreux verger, système cultural et principe esthétique dans lequel se glissent des archipels relationnels: aires de jeux, plateformes d'échanges, piste de vélo ou de courses spontanées pour les enfants.L'architecture, à la frontière entre ville et parc, reflète, prolonge le paysage pour les passants et permet depuis les appartements de profiter du panorama en cinémascope. La vitre sans teint garantit l'intimité des occupants.L'ensemble des logements profite de terrasses généreuses. Les espaces de vie et les chambres ont des accès directs à ces prolongements extérieurs.Le pôle hôtelier suit la logique urbaine en bandes du Parc des Expositions dessiné par OMA. Il s'inscrit dans une série de bâtiments à très grande échelle. Le projet s'établit comme un lieu d'intensité permanente branché à la rue centrale du Pex, épine dorsale des nouvelles infrastructures.Un voile verrier aux différentes qualités de transparence diffracte et reflète, faisant disparaitre la mesure du percement et la répétition de la fenêtre de chambre. La couleur générale du projet provient de celle des matériaux et de l'environnement de l'ensemble du PEx.Le rez-de-parvis en mosaïque ordonne une grande diversité de programmes tout en identifiant les différents fluxs. Restaurants, commerces, coworking et zones de chalandise s'expriment en façade. Aux étages, trois émergences accueillent l'hôtel 5* et son executive floor, l'hôtel 3* et l'espace bien-être.Dès le rez-de-chaussée le visiteur réalise un voyage au coeur d'une structure expressive d'arches successives. La structure Vierendeel permet une grande souplesse formelle en plan et de grands franchissements qui offrent une grande économie de points porteurs au rez-de-chaussée.Le projet est un repère identifiable dans un paysage infrastructures XXL. Sa richesse programmatique en font un lieu attractif qui s'adresse aux usagers du Pex et plus largement aux Toulousains.La villa partagée, échelle domestique du quartierUne intention forte du projet a été de libérer le RDC et de placer tout les logements dans les étages, ce qui permet de préserver leur qualité et leur intimité.
   Le RDC est voulu ouvert et central, entre le parc à l'Ouest, et une place en cœur d’ilot à l'Est. Il offre des équipements et des services communs afin de dynamiser la vie de quartier : un dojo et ses annexes, une salle de sport, des stationnements vélos.L'ensemble s'inscrit dans l'alternance de gabarits hauts et d’espaces publics mis en place par la ZAC. La hauteur des bâtiments libère le sol et définit l’espace public. La programmation des rez-de-chaussée anime la place.Les nouveaux bâtiments dessinent les contours de la nouvelle place. Les usages en rez-de-chaussée prolongent l'espace public jusque dans le patio de la Résidence Service Senior.Au-delà la seconde ceinture de boulevards, de grandes routes qui convergent vers le centre-ville définissent un tissu diffus. L'écoquartier de la Salade fera de ce morceau de ville une respiration animée et vivante. La parcelle est la pièce manquante entre un contexte très urbain et un ensemble d’équipements ouverts sur un parc.Le projet opère la mise à l’échelle entre l’axe routier structurant la ville et le chemin de l’école. Il adopte une écriture étagée qui affirme l'horizontale de l'Avenue de Fronton. Le rez-de-chaussée s'inscrit dans la dynamique de programmation de la Salade: un ensemble vivant à toute heure de la journéeLa façade des trois étages courants reprend le rythme du rez-de-chaussée et répond aux nécessités structurelles et d’usage des terrasses. Les poteaux sont les séparatifs entre les terrasses des logements. Les deux derniers niveaux accueillent de grands appartements et des duplexs privilégiant des typologies traversantes ou multi-orientées.
`;
