export const text = `Le patrimoine dans la nouvelle région Occitanie
Source : Département de la politique des publics, Direction générale des patrimoines
La nouvelle région Occitanie est après la région Nouvelle Aquitaine la plus dotée de France en termes de patrimoine bâti et de musées. La suivent de près, Auvergne-Rhône-Alpes et Grand Est. Ci-dessous, sauf exception les derniers chiffres consolidés, datant de 2014, de la base de données Patrimostat du ministère de la Culture et de la Communication.
133 musées, 11 CMN, 1474 MH classés, 3285 MH inscrits, 21 VPAH, 5 CIAP, 20 MDI, 3,4 millions de visiteurs dans les musées , +24 % évolution de fréquentation des musées 2011/2014
Les villes historiques les plus « robustes » le doivent souvent à deux critères : leur situation sur des voies importantes de communication et la multiplicité des fonctions urbaines qu’elles accueillent. Les villes économiquement les plus dynamiques se sont beaucoup développées entre la fin du XIXe siècle et 1950. Leur centre historique traditionnel s’est alors trouvé entouré d’importants quartiers nouveaux, souvent en rupture avec la structure urbaine ancienne. La période de l’après-guerre a été marquée par l’application des théories de l’urbanisme moderne et notamment par une organisation spatiale dissociant les fonctions urbaines sur le territoire. Ces nouveaux tissus urbains sont en discontinuité réelle avec la ville telle que constituée jusque-là. La forme architecturale et urbaine des constructions est sans rapport avec celle des parties anciennes de la ville. C’est une architecture produite sur une base industrielle, des matériaux et un registre formel sans rapport avec le territoire et avec la culture locale. C’est une architecture aux références internationales.
Comment une ville, aujourd’hui confrontée à un centre historique en perte de dynamisme et à des quartiers contemporains reconnus dégradés, peut bâtir une stratégie d’aménagement et de développement qui fonde un projet réunifiant ces deux morceaux de ville, trop longtemps dissociés dans le récit local, dans l’appréhension de l’identité urbaine partagée ?
La récente géographie prioritaire reconnaît dorénavant des centres anciens aux côtés des quartiers d’habitat social. Parce que fragilisés, voire dégradés, ils font maintenant l’objet d’un même dispositif, celui de la politique de la ville voire celui d’un programme de renouvellement urbain. Ils ont des caractéristiques communes comme le profil socio-économique des populations ou leur enclavement réel ou symbolique. Mais ils sont également très différents. Leurs situations géographiques par rapport à la ville et aux réseaux de communication, leurs formes urbaines, leurs historicités et leurs valeurs symboliques, le confort de l’habitat… Les cœurs historiques et les quartiers d’habitats récents n’ont pas les mêmes atouts et les mêmes difficultés.
La Rencontre d’Auch, « Centre ancien et Politique de la ville », est une des toutes premières fois où seront associés dans la même réflexion ces deux réalités qui participent de notre vie urbaine. Pour oser se donner l’enjeu de faire des quartiers d’habitat récents dégradés des lieux de destination pour tous et des quartiers anciens des lieux de résidence, de vivre ensemble…

Le patrimoine entre de manière très nouvelle dans les projets urbains, touristiques et culturels. Il interroge les enjeux de la ville, dans une vision contemporaine de la ville durable, d’une ville où la qualité urbaine rime avec le vivre ensemble, où l’innovation se déploie au cœur des fonctions urbaines, où la culture se métisse et se projette comme carrefour des identités. Le passé et le futur de nos villes parlent ensemble de cette richesse patrimoniale et les preuves d’attachement de la population sont nombreuses. Tout en sachant que le patrimoine est un sujet encore trop souvent réservé aux spécialistes… Il s’agit de façonner ensemble les récits de nos villes, au moment de l’affirmation forte du fait urbain et métropolitain.
En créant la Biennale européenne du patrimoine urbain, l’association du Dialogue métropolitain de Toulouse propose aux habitants, aux acteurs, aux territoires, un rendez-vous innovant pour faciliter une connaissance mieux partagée, dans une perspective démocratique. Cette première édition 2016 s’inscrit dans un contexte porteur, avec la Loi liberté de Création, Architecture et Patrimoine qui propose une articulation nouvelle pour la question patrimoniale dans les projets urbains et dans les politiques territoriales de développement, à partir de la notion de « site patrimonial remarquable » ; avec la stratégie engagée par la Caisse des Dépôts au plan national pour lutter contre le déclin des centres-villes, très souvent fortement impactés par la dimension patrimoniale, dans son dispositif « centres démonstrateurs » ; par une inflexion de la politique nationale en matière d’appui aux centres bourgs, désormais étendue à l’échelle de 50 000 habitants et augmentée par la nouvelle géographie prioritaire de la Politique de la ville ; enfin, avec deux missions nationales de réflexion, sur la question des centres historiques, conduite par Yves Dauge, et sur l’attractivité et le tourisme, conduite par Martin Malvy. La dimension européenne est présente tout au long de la Biennale : à Cahors, avec le réseau de l’Association nationale des villes et pays d’art et d’histoire et le projet européen d’innovation pour la reconquête du centre ancien cadurcien ; à Carcassonne, avec une inflexion méditerranéenne autour du sujet du patrimoine mondial ; au Quai des Savoirs, à l’écoute du représentant de la Direction générale aux Régions sur la stratégie européenne de l’agenda urbain.
Au terme de cette première édition de la Biennale européenne du patrimoine urbain, le 14 novembre constituera un moment privilégié pour prendre ensemble la mesure des chantiers de développement à engager et pour comprendre l’importance d’associer plus que jamais les habitants, les associations, les acteurs, à une connaissance partagée, à la quête de valeurs communes, à l’architecture, à la création contemporaine… à la fabrique du récit des villes.

Et si vous visitiez la ruche du Quai des Savoirs ?

Durant le week-end métropolitain des 12 et 13 novembre, la Biennale européenne du patrimoine urbain fait le choix de l’expérimentation au Quai des Savoirs, équipement culturel métropolitain de Toulouse dédié à la diffusion de la culture scientifique et au partage d’expérience. L’entrée est libre et gratuite mais la jauge de fréquentation étant limitée, la réservation préalable est hautement conseillée pour les conférences et autres formats de diffusion proposés lors de cette séquence. Quelques fonctions continues de la ruche vous sont ici présentées.

Les workshops de l’Atelier métropolitain
Impliquant quelque 250 étudiants et encadrants – tous ayant travaillé en amont dans la halle d’exposition du Quai des Savoirs –, les workshops seront en phase d’accrochage et de restitution lors du week-end d’ouverture au grand public. Joyeuse ruche dans laquelle butiner, avec l’aide des médiateurs, en allant à la rencontre des hypothèses, essais et expérimentations urbaines qui seront présentés alors, avec les atours de l’inachèvement, sans prétention aucune… (voir la présentation page suivante de l’Atelier métropolitain)

Les projections sous la bulle
Vous ne pourrez pas la rater, L’architecture gonflable conçue par Hans-Walter Müller avec les étudiants de l’ISDAT, Institut supérieur des arts de Toulouse, option Design, est un salon de cinéma qui accueille une programmation de courts et moyens métrages proposée par Image de Ville. (voir la présentation p.32)

Mouloud Akkouche
Auteur de romans policiers, récits, nouvelles, pièces radiophoniques, scénario et livres jeunesse, Mouloud Akkouche aborde l’écriture comme un moyen de témoigner de son temps et d’injecter de la fiction dans le réel qu’il aime observer, l’environnement urbain au premier titre. Parmi ses nombreuses parutions, Cayenne, mon tombeau (Flammarion, 2002), Balle perdue (Le Seuil, 2007), Si à 50 ans, t’as pas ta Rolex (Atelier IN8, 2012), Résidente (Court circuit, 2016).

Raphaële Bertho
Historienne de l’art, enseignant à l’université de Tours, Raphaële Bertho est spécialiste de la photographie de paysage. Auteure de nombreux articles de référence, elle a publié en 2013 La Mission photographique de la DATAR, Un laboratoire du paysage contemporain (La Documentation française). Commissaire associée d’une exposition à la BnF sur la photographie de paysage en France (2017), Raphaële Bertho accompagne aussi le collectif d’auteurs France(s) Territoire Liquide depuis 2012.

Ulrich Lebeuf
Reporter de presse régulièrement publié par les grands quotidiens et magazines nationaux, membre de l’agence MYOP, Ulrich Lebeuf développe un travail de recherche personnel sans entrave, en moyen format ou en Polaroïd, de la couleur au noir et blanc, de l’argentine au numérique. Parmi ses publications récentes, Antonyme de la pudeur (Le château d'Eau, 2010), Territoires du tramway (Privat, 2010), Tropique du cancer (Charlotte Sometimes, 2016). Alis Mirebeau l’a assisté pour les prises de vue du livre Des miettes d’étoiles derrière soi.

Les workshops de l’Atelier métropolitain
Habitée et investie par les étudiants des workshops de l’Atelier métropolitain, la ruche de la Biennale au Quai des Savoirs, à Toulouse, ouvre grand ses portes pendant deux jours, les 12 et 13 novembre. De nombreuses formations se sont engagées dans cette démarche, en partie itinérante auprès des collectivités de la région Occitanie.

Hans-Walter Müller appartient à une espèce de créateur rare, celle des utopistes à la convergence des arts, mais qui n’ont jamais lâché leur affaire. « Je ne fais pas trop de distinction entre un architecte, un artiste et un sculpteur », explique celui qui démarre sa carrière par l’étude de l’architecture à l’Université de Darmstadt en 1961. Hans-Walter Müller poursuit ses études à Paris et engage sa recherche architecturale avec les matériaux de son temps : la lumière artificielle, l'image projetée, la matière plastique, les moteurs électriques, au service de « l’architecture du mouvement » (1965). Lauréat de la Biennale de Paris de 1965, lauréat du pavillon allemand à l’exposition internationale de Montréal en 1967… Il appartient au mouvement d’Art cinétique et est le créateur des « Gonflables », constructions à structure de plastique et mises en tension par l’air sous pression. Il a collaboré avec des artistes comme Jean Dubuffet, Salvador Dalí ou Maurice Béjart… La Cité de l’architecture et du patrimoine lui consacrera une grande exposition monographique en 2018.
Un piéton de l’air
Certes, dans une Biennale qui a pour vocation d’honorer le patrimoine bâti, gageons qu’il y a une sorte de paradoxe à convier cet inventeur de structures épatantes, d’églises gonflables de “39 kilos pour 200 fidèles”, de décors de scène, de villages de vacances pop-up et notamment d’une maison dans laquelle il vit, près d’un aérodrome, depuis plus de quarante ans, en suspension entre la terre et le ciel : « je suis un piéton de l’air, si les choses sont casse-gueule, on ne se casse pas la gueule ! »
Après les marges de la ville en 2015, le festival Image de ville porte cette année son regard sur la jeunesse dans la ville. Comment ces citadins – pas encore adultes, sont-ils considérés et accueillis par la ville des adultes ? Quelle place leur accorde-t-elle ? Quels sont leurs pratiques, leurs usages et leurs aspirations ? « Bonjour la jeunesse ! » se déroule entre le 11 et le 20 novembre 2016 pour 8 journées de projections, rencontres et débats, à Aix-en-Provence (11/13 nov.), Martigues (16 nov.), Port-de-Bouc (17 nov.) et Marseille (18/20 nov.). Renseignements sur www.imagedeville.org

	•	Architecture et patrimoine du XXe siècle en France, de Bernard Toulier, Éditions du patrimoine. Cet ouvrage propose une lecture de l’architecture moderne et contemporaine au début de XXIe siècle.

	•	Découvrir l’architecture, de Steen Eiler Rasmussen, Éditions du Linteau. Loin des démonstrations savantes et de nos références culturelles, l’auteur nous fait découvrir ce que sont les espaces que nous traversons tous les jours, ce qui fait la qualité d’un lieu, le pourquoi du charme des bâtiments anciens les plus anodins…

	•	Patrimoine architectural urbain et paysager : enjeux juridiques et dynamiques territoriales, de Marie Cornu, Marie-Agnès Férault et Jérôme Fromageau, L’Harmattan.Ce livre est centré sur les zones de protection du patrimoine architectural, urbain et paysager (ZPPAUP) qu’il aborde selon trois angles : la diversité des patrimoines, l’outil de gestion du patrimoine, l’outil de développement local.

	•	De la ville au patrimoine urbain – Histoires de forme et de sens, de Lucie K. Morisset et André Corboz, Presses de l’Université du Québec.Pourquoi y a-t-il la ville et pas autre chose ? Que signifient les images auxquelles nous recourons pour en parler ? Comment décoder nos interrelations avec le territoire ? Telles sont les questions qui animent cet ouvrage.

	•	L’allégorie du patrimoine, de Françoise Choay, Éditions du Seuil. Pourquoi le patrimoine historique, architectural et urbain a-t-il conquis aujourd'hui un public planétaire ? Pourquoi sa connaissance, sa conservation et sa restauration sont-elles devenues un enjeu pour les états du monde entier ?

	•	Le patrimoine en questions. Anthologie pour un combat, de Françoise Choay, Éditions du Seuil. Un livre de référence dans lequel l’auteure explique, à l’instar de Viollet-le-Duc, que le meilleur moyen de conserver un édifice, c’est de lui trouver un emploi.

	•	Les 101 mots de la ville à l’usage de tous, de Frédéric Lenne, Éditions Archibooks.À travers des villes, l’auteur explore la ville : des rouages administratifs, politiques et culturels qui la composent aux quotidiennetés qui façonnent pour chacun une image presque intime du lieu.

	•	Patrimoine en poche ! Centre régional des lettres Midi-Pyrénées. Une balade dans les fonds écrits, graphiques et sonores de Midi-Pyrénées. Une invitation à parcourir le territoire midi-pyrénéen à travers ses fonds.

	•	Petit traité des grands sites, de Jean-Pierre Thibault, Actes Sud. Ce traité repose sur l’expérience de la politique des Grands Sites, initiée et pilotée par le ministère chargé de l’environnement depuis 1976. Il s’enrichit également d’exemples de sites étrangers et d’éclairages apportés par la gestion des sites inscrits sur la liste du patrimoine mondial de l’Unesco.

	•	Pour une politique de l’architecture, de Max Querrien, Éditions du Patrimoine. Au fil du récit de son parcours, l’auteur évoque les contradictions qui affectent la démarche architecturale, les malentendus qui la rendent souvent mal comprise, l'autisme d'une bonne partie de la population à son sujet, la passivité où se tiennent souvent les responsables à l'égard d'une discipline qui détient pourtant les clés de notre cadre de vie.

	•	Restauration des façades des monuments urbains, ministère de la Culture et de la Communication, Éditions Dominique Carré. Quatre architectes en chef des monuments historiques donnent les clés de leur pratique, insistant chacun sur un aspect culturel ou technique : état des lieux des pratiques, esprit de la restauration, matériaux, authenticité, diagnostic et méthode.

	•	Un siècle de construction, ouvrage collectif en 2 tomes, sous la direction de Frédéric Lenne, Éditions du Moniteur. Ce livre explore les constructions en France au cours du XXe siècle dans un premier volume, composé de deux parties (1900-1945 et 1945-2000), qui adopte une approche chronologique organisée en une série de séquences thématiques. Le second volume traite de quelques grands dossiers transversaux qui caractérisent le siècle de constructions : évolution du logement, des styles, ameublement, jardins, paysages...

	•	Viollet-le-Duc, de Françoise Bercé, Éditions du patrimoine. Fut-il un passeur du modernisme ou un attardé de l’historicisme ? Au gré des successives réinterprétations du passé et des récentes découvertes, l’auteure nous fait rencontrer l’homme dans sa complexité et nous révèle l’immense richesse de son œuvre.


Dialoguer à l’échelle d’une région métropolitaine ?
Entretien avec Robert Marconis

Le Dialogue métropolitain de Toulouse n’est pas une unité administrative, un échelon territorial doté de compétences en propre, mais l’expression d’un réseau de villes qui souhaite construire petit à petit une lecture partagée de ce qui fonde leur territoire commun dans sa dimension urbaine et métropolitaine. Robert Marconis pose ici les jalons qui permettent d’apprécier les composantes géographiques de ce « dialogue », lequel s’incarne aujourd’hui dans cette première Biennale européenne du patrimoine urbain.

Au sein de la nouvelle grande région Occitanie, la métropole toulousaine est liée à des villes moyennes et à leurs territoires respectifs. Le Dialogue métropolitain de Toulouse incarne une association de collectivités territoriales qui expriment ensemble leur dimension urbaine. En tant que géographe et fin connaisseur de la constellation territoriale toulousaine, quelle définition donneriez-vous de cette construction métropolitaine ?
Une métropole est une grande ville qui organise la vie urbaine et régionale autour d’elle. Cette définition simple recouvre évidemment une réalité autrement plus compliquée à cerner. En 2014, le législateur a seulement retenu un critère démographique, attribuant le statut de métropole aux EPCI (Établissements publics de coopération intercommunale), communautés urbaines ou communautés d’agglomération qui comptaient plus de 400.000 habitants dans une aire urbaine de plus de 650 000 habitants. Brest et Montpellier, puis Nancy, en 2016, qui ne répondaient pas à ce critère, ont également demandé et obtenu ce statut.
Dans la nouvelle région Occitanie, il y a donc deux métropoles, Toulouse et Montpellier autour desquelles s’organisent deux systèmes urbains aux configurations géographiques différentes, qui fonctionnent de façon autonome, comme en témoigne les cartes des migrations domicile-travail. Ils correspondent globalement à chacune des deux régions fusionnées, Midi-Pyrénées et Languedoc-Roussillon : l’un organisé en étoile autour de Toulouse, mais qui inclut Carcassonne ; l’autre en forme de chapelet qui va de Nîmes à Perpignan. Historiquement, depuis l’Antiquité, il y a toujours eu des relations d’intensité variable, mais souvent complémentaires, entre ces deux systèmes territoriaux.
Au début des années 1960, l’ancienne capitale de la province de Languedoc, Toulouse, devenue simple chef-lieu de département en 1790, a été promue capitale d’une « circonscription administrative régionale », appelée Midi-Pyrénées, regroupant huit départements placés sous l’autorité d’un Préfet de Région, en 1964. Toulouse accueillit ainsi les services déconcentrés de l’État à vocation pluri-départementale. Au même moment Bordeaux et Montpellier furent choisies comme capitales administratives de l’Aquitaine et du Languedoc-Roussillon. Il faudra attendre 1972 pour que ces circonscriptions administratives deviennent officiellement, sans modification de leurs limites, des « Régions » dotées d’institutions spécifiques (Conseil régional, Comité économique et social), dont les compétences seront étendues avec les lois de décentralisation, à partir de 1982.
En même temps que s’opérait cette réforme administrative, la politique nationale d’aménagement du territoire, placée en 1963 sous l’autorité de la DATAR (Délégation interministérielle à l’aménagement du territoire et à l’action régionale), choisissait de lutter contre le déséquilibre Paris-province en réorganisant le territoire français autour de huit villes, dont Toulouse, qui se virent  attribuer le rôle de « métropoles d’équilibre ». Dans un contexte de croissance économique forte, ces villes ont alors reçu de l’État une part des fruits de celle-ci, sous la forme de grands équipements et d’emplois publics  à vocation régionale (santé, recherche, enseignement supérieur…), et ont eu pour mission d’accueillir des activités économiques nouvelles, en partie décentralisées depuis la capitale. Tel fut le cas à Toulouse pour des activités confortant une spécialisation ancienne dans le domaine de l’aéronautique et de l’espace (grandes écoles, CNES…).
Ainsi, dans les années 1960, Toulouse a été confrontée à une double injonction métropolitaine. Le « grand village » qu’elle était encore au début des années 1960 est entrée  à marche forcée dans la modernité et a dû s’organiser pour assumer son nouveau rôle de métropole administrative et de métropole économique. C’est l’époque des grandes opérations d’urbanisme, dont le symbole est la « ville nouvelle » du Mirail. Toulouse connaît alors un dynamisme vigoureux, accompagné d’une forte croissance démographique, que la crise économique des années 1970-1980 n’a pas remis en cause.
Mais ce dynamisme est essentiellement resté le fait de la métropole toulousaine, et le déséquilibre entre celle-ci et le reste de la région s’est fortement accru. L’écart s’est alors creusé avec les « villes moyennes » situées dans son orbite.

Ce déséquilibre ne compromet-il pas un « dialogue » entre Toulouse et les villes moyennes de la région…

On a beaucoup évoqué à ce propos le déséquilibre souvent dénoncé au plan national entre « Paris et le désert français ». Il est vrai que pendant plus d’un siècle, jusqu’au début des années 1960, Paris a capté l’essentiel de la croissance urbaine, et concentré les fonctions économiques, politiques et culturelles du pays. D’où la volonté de mettre fin à ce processus, aux effets pervers multiples, par une politique volontariste d’aménagement du territoire. Les métropoles d’équilibre avaient pour objectif de promouvoir un développement plus équilibré. Se référant aux travaux de l’économiste François Perroux, elles devaient devenir des « pôles de croissance » dans lesquels on attendait que l’accumulation des grands équipements et des activités induise une dynamique économique qui se diffuserait ensuite à l’ensemble de l’espace régional. Les villes moyennes devaient donc, à terme, bénéficier des « retombées » de cette croissance métropolitaine.
On comprend volontiers l’inquiétude qui a pu gagner alors ces villes situées dans l’orbite de Toulouse (Albi-Carmaux, Castres, Montauban, Auch, Cahors…), connectées à elle par un réseau de communication en étoile façonné, et progressivement renforcé, depuis le début du XIXème siècle. Souvent confrontées à la crise d’industries anciennes (textile, mégisserie, charbonnages…), elles redoutaient d’attendre trop longtemps les retombées d’un dynamisme toulousain, qui a longtemps semblé bien incertain, et de voir leurs habitants migrer vers la métropole devenue encore plus attractive par son potentiel d’emplois et ses équipements.
Pour lever ces inquiétudes, à partir de 1973, l’État par le biais de « contrats villes-moyennes » a décidé de leur apporter des aides spécifiques qui ont bénéficié à Rodez, Albi, Castres, Carcassonne, Auch…

De quelles cartes disposait la métropole toulousaine pour inscrire son développement dans le territoire régional ?

Quand Toulouse fut investie des fonctions de métropole, la configuration du territoire qui s’organisait autour d’elle, et que l’on commençait à nommer Midi-Pyrénées, n’était pas aussi artificielle qu’on a pu l’écrire. On a plutôt pris acte des relations multiples et complexes qui s’étaient nouées depuis la fin du XVIIIème siècle entre Toulouse et son environnement régional. Un élément fort qui explique la consolidation d’un système urbain régional autour de Toulouse fut l’organisation des infrastructures de transports, en particulier la formation de l’étoile ferroviaire que nous connaissons aujourd’hui. C’est un héritage de la politique de l’État et de l’entreprise concessionnaire du réseau de chemins de fer, la Compagnie des Chemins de Fer du Midi.
Transgressant les limites administratives des départements, les relations économiques entre Toulouse et une vaste région n’ont cessé de se renforcer. Ainsi, lorsque fut envisagée, dès l’entre-deux-guerres, la création de « régions économiques », Toulouse s’imposa comme le centre de l’une d’entre elles, au sein de laquelle furent associées plusieurs chambres de commerce des départements voisins. Le grand géographe Paul Vidal de La Blache, tout comme l’historien Henri Hauser, on contribué à cette réflexion sur un découpage régional, associant plusieurs départements dont l’identité s’était peu à peu affirmée depuis leur création en 1790. Dès 1910, Vidal de la Blache proposait de créer autour de Toulouse, qui en serait le centre d’impulsion, une région économique dont les contours sont très proches de ceux de la future région Midi-Pyrénées (« Revue de Paris », 1910). Il allait même jusqu’à proposer d’y rattacher Castelnaudary, voire Carcassonne, et de redessiner ainsi le département de l’Aude, anticipant déjà sur la réflexion qui est celle, un siècle plus tard, de l’actuel Dialogue métropolitain…
Beaucoup plus tard, dans les années 1950, toujours dans un souci de dépasser des limites départementales, de plus en plus mal adaptées aux réalités et aux politiques économiques territoriales, plusieurs découpages ont été utilisés, pour organiser, toujours autour de Toulouse, dont la suprématie ne fut jamais contestée, des « régions » qui furent ainsi placées pour les questions économiques ou d’aménagement sous l’autorité du représentant de l’État, siégeant dans cette ville : commissaire de la République en 1944, puis Préfet IGAME (Inspecteur général de l’Administration en Mission extraordinaire »). Afin de préparer l’un des « programmes d’action régionale » prescrits par décret en 1955, une « région de programme du Midi et des Pyrénées » fut définie autour de Toulouse : elle incluait alors, outre les départements de la future région Midi-Pyrénées, l’ensemble de la chaîne des Pyrénées, c’est-à-dire les Pyrénées atlantiques et les Pyrénées orientales, qui furent ensuite rattachés administrativement, l’un à l’Aquitaine, l’autre au Languedoc-Roussillon.
La promotion de Toulouse au rang de métropole dans les années 1960 a sans doute sorti la région de la spirale du déclin démographique et économique qui la caractérisait depuis le milieu du XIXème siècle : entre 1850 et 1954, elle avait perdu près du quart de ses habitants ! Le renouveau fut ensuite spectaculaire mais il a bénéficié essentiellement à la métropole toulousaine. Au plan démographique, jusqu’à la fin des années 1990, son aire urbaine de plus en plus étendue (342 communes sur la base du recensement de 1999) fut la grande gagnante. Et sa croissance s’est poursuivie : avec désormais 453 communes elle compte aujourd’hui près de 1,3 million d’habitants, soit 42% de la population de Midi-Pyrénées, gagnant chaque année, à elle seule, près de 18 000 habitants, soit 3,5 fois plus que l’ensemble des autres aires urbaines de la région. Un constat qui nourrit  toujours l’idée que Toulouse « vampirise » sa région et contribue à accentuer en son sein les déséquilibres territoriaux. (S. Thépot, « Comment raccrocher les wagons à la locomotive toulousaine, L’image d’une ville qui « vampirise » sa région devient insupportable », Le Monde, 1er mars, 1998).

Vous soutenez qu’il faut contester ce discours convenu, notamment en examinant de plus près les processus démographiques, d’une part, mais en vous appuyant aussi sur des phénomènes plus complexes…

Dans une région qui a une longue histoire rurale, je constate d’abord que le fait urbain,  a souvent été perçu de façon très négative, au nom d’une « ruralité » parée de toutes les vertus, qu’il menacerait.
Du point de vue démographique les processus vont pourtant à l’encontre de cette interprétation. J’en avais fait la démonstration avec l’Insee dès les années 1970. Elle s’est confirmée ensuite à chaque recensement. En fait la croissance de la population toulousaine doit très peu aux apports de la région. Ce qui a fait la différence entre l’aire urbaine de Toulouse et les autres villes de la région, c’est la capacité de la métropole toulousaine, du fait de ses fonctions urbaines, à être largement bénéficiaire dans ses échanges avec le reste de la France et avec l’étranger, qui lui fournissent quelques 80 % de son solde migratoire. J’ajoute toutefois que, depuis une vingtaine d’années, les villes moyennes proches de Toulouse voient peu à peu leurs soldes migratoires s’améliorer, comme si elles bénéficiaient désormais d’une attractivité de type métropolitain, dans leurs échanges de population avec des territoires situés hors de Midi-Pyrénées.
Par ailleurs l’amélioration des liaisons entre Toulouse et quelques villes moyennes ouvre sans doute le marché du travail de la métropole toulousaine à des populations résidant dans ces villes moyennes, au prix de longs déplacements quotidiens – parfois assortis de mouvements  plus faibles en sens inverse, vers Montauban, Auch, Albi, Pamiers, voire Castelnaudary… De la même façon des artisans ou des entreprises de ces villes peuvent s’y pérenniser, voire s’y développer, en n’hésitant pas à répondre à une demande sans cesse accrue et diversifiée au sein même de l’aire urbaine de Toulouse, autour de laquelle s’esquisse donc une sorte d’« aire métropolitaine » multipolaire, en étoile. Le « dialogue métropolitain » s’y décline peut-être aussi dans les domaines de l’emploi et de la vie économique. Ce qui conduit à revoir un discours sans doute trop négatif sur la métropolisation : la locomotive toulousaine, qui a porté la croissance régionale depuis un quart de siècle, commencerait-elle enfin à tirer plusieurs wagons ? Cette hypothèse mériterait sans doute des études plus fines.
La naissance de l’Association du Dialogue métropolitain de Toulouse, le 8 avril 2013, s’inscrit dans ce contexte. Elle marque une volonté de rupture avec le discours dominant, simplificateur, qui, depuis plusieurs décennies, opposait le dynamisme d’une agglomération toulousaine, promue «métropole » dès les années 1960-1964, au reste de sa région, considéré comme son « arrière-pays », qu’elle aurait contribué à vider de ses forces vives et dont elle aurait compromis le développement. Cette lecture du mouvement de métropolisation, qui a certes très largement et très longtemps profité à l’aire urbaine de Toulouse, repose davantage sur des constats sommaires, non dépourvus parfois d’arrière-pensées politiques, que sur des analyses scientifiques qui doivent prendre en compte des processus beaucoup plus complexes, qu’il convient de replacer dans la longue durée.

Quelles perspectives pour le Dialogue métropolitain de Toulouse dans le domaine de l’aménagement territorial ?

La volonté d’engager aujourd’hui un « dialogue » entre la métropole et les autres agglomérations placées dans son aire d’influence apparaît bien comme une rupture. C’est une première étape essentielle pour jeter les bases d’un diagnostic partagé des concurrences et des solidarités qui affectent le « système urbain » auxquels elles participent, organisé en étoile autour de Toulouse. Ce diagnostic est indispensable à la mise en œuvre d’une véritable coopération territoriale au service de l’intérêt général d’un vaste territoire et de ses habitants. Une coopération qu’il convient de concevoir à différentes échelles, et désormais à l’échelle de la grande région Occitanie, afin de valoriser les atouts de tous les territoires concernés, sans nier leurs spécificités, leurs contraintes et leurs handicaps. Une coopération rompant avec les inquiétudes et la méfiance suscitées par une ambition hégémonique supposée de la métropole toulousaine au sein de ce qui fut une construction territoriale, Midi-Pyrénées, dont elle a largement contribué au développement et à façonner l’identité. Rompant aussi avec les errements de schémas de rééquilibrage du territoire régional, trop souvent fondés sur des objectifs qui relevaient d’autant plus de l’incantation qu’ils étaient non prescriptifs  et ne prenaient guère en compte la complexité des processus à maîtriser, économiques, sociaux, politiques, environnementaux et culturels.

Sur demande du comité du patrimoine mondial, l’Etat s’est engagé à renforcer les outils de protection des abords du Canal du Midi. Sous votre autorité, une mission a été mise en place pour définir les modalités d’une nouvelle gouvernance de la gestion de ce bien. En quoi consiste cette mission ?
Cette mission vise trois objectifs : coordonner la gestion du Canal du Midi et de ses abords, veiller à l’appropriation et à la diffusion des valeurs que ce bien symbolise – notamment le développement durable – et mettre en œuvre des actions stratégiques rassemblant l’État et les collectivités territoriales, au premier rang desquelles figure la Région.
J’ai confié le pilotage de cette mission à Mme Marie-Thérèse Delaunay, sous-préfète et directrice de projet en charge du Canal du Midi. À ce titre, elle travaille en lien étroit avec l’ensemble des services déconcentrés de l’État et l’opérateur public Voies navigables de France (VNF). Elle anime une véritable équipe composée, notamment, de M. Philippe Mercier chargé d’identifier les grands enjeux relatifs au Canal, s’agissant du patrimoine bâti, de la culture et de l’éducation ; de Mme Katia Bonningue, missionnée pour traiter des questions d’aménagement et d’environnement comme le projet d’extension du classement UNESCO et, enfin, du directeur territorial de VNF, M. Jean Abèle, qui coordonne la gestion des voies d’eau.
Quel est le rôle du « comité du bien » qui vient d’être créé et pourquoi le Canal avait-il besoin de pareille instance de gouvernance ?
Notons, tout d’abord, que le Canal du Midi n’est pas le seul bien UNESCO à disposer d’un comité dédié. Les Chemins de Saint-Jacques et le Val de Loire sont également dans cette situation.
Sur la liste du patrimoine mondial de l’UNESCO, le Canal du Midi, ainsi que les sept autres sites classés de notre région, côtoie des ensembles patrimoniaux aussi prestigieux que le Château de Versailles ou la lagune de Venise. L’action que nous menons doit donc viser l’excellence. Pour cela elle doit être cohérente. Or les acteurs impliqués directement ou indirectement sur le Canal sont nombreux. La mise en place d’un comité de bien me semblait donc nécessaire pour pouvoir tous les réunir et travailler de concert. Signe de son importance, nous avons choisi le château de Bonrepos-Riquet – la demeure historique du concepteur du Canal, Pierre-Paul Riquet – pour tenir la première séance de ce comité le 22 juin dernier.
Une grande région, 4 départements, 90 communes, 20 EPCI, les chambres consulaires, les parlementaires, les opérateurs de tourisme, les plaisanciers, les bateliers, l’Agence de l’Eau, les pêcheurs, les associations, les experts et universitaires et la société civile… Comment peut s’organiser le travail avec autant de parties prenantes ?
Comme vous le sous-entendez, la multitude des parties peut être un facteur de blocage pour le Canal du Midi. Notre défi est d’en faire une force. Pour cela nous mobilisons ou mobiliserons plusieurs outils.
Je pense, dans un premier temps, aux « ateliers du Canal du Midi » qui se réunissent dès ce mois d’octobre. Ces ateliers seront avant tout des espaces d’échanges destinés à faire émerger des diagnostics partagés sur les menaces susceptibles d’altérer la valeur exceptionnelle du Canal ainsi qu’une culture de la concertation dans sa gestion à long terme. Qu’il s’agisse en effet du « chancre coloré », un champignon attaquant les platanes qui fondent l’identité visuelle du Canal, de la question de la qualité des eaux, des voies vertes ou du développement touristique, les points de vue sont nombreux mais ne sont pas nécessairement convergents. Il faudra donc les concilier dans ce cadre.
Je pense également aux commissions locales qui se réuniront à partir du mois de janvier 2017. Ces commissions déclineront, à l’aval des « ateliers », des plans d’actions opérationnels visant à assurer la bonne conservation du Canal. Un conseil scientifique veillera à la qualité et à la faisabilité des actions proposées.
Je pense, enfin, au plan de développement durable ou plan « Canal ». Ce plan, élaboré pour cinq ans, comportera trois volets : la valorisation patrimoniale et culturelle, l’économie et la protection environnementale. Carole Delga, la présidente du Conseil régional et moi-même en avons présenté le budget qui sera de 230 millions d’euros. Il permettra de couvrir l’entretien ou la restauration des infrastructures du Canal, de ses équipements, de ses berges et plantations, de ses ouvrages hydrauliques et du château de Bonrepos, sans oublier le développement des actions culturelles et la gestion de la qualité des eaux. Une sorte de « commando », c'est-à-dire une équipe réduite et hautement qualifiée, réunie dans une structure de type Groupement d’intérêt public, sera alors chargée de coordonner la mise en œuvre de ces actions.
Le Canal du Midi est un trait d’union entre les anciennes régions Languedoc-Roussillon et Midi-Pyrénées. Son 350ème anniversaire, concomitant à la fusion des régions, est donc l’occasion d’en faire le symbole de l’identité et du projet que nous portons pour la nouvelle région Occitanie : un projet d’ambition et de cohésion.
Les projections sous la bulle
Au Quai des Savoirs, l’architecture gonflable conçue par Hans-Walter Müller avec les étudiants de l’ISDAT, Institut supérieur des arts de Toulouse, option Design (voir pages 25-26) est un salon de cinéma qui accueille une programmation de courts et moyens métrages proposée par Image de Ville. Une programmation qui nous fait voyager dans l’univers des villes, qui pose un regard distancié sur leur morphologie, leurs héritages, les liens qui s’y tissent en permanence… Un langage vidéo contemporain, en boucle continue, entre l’installation artistique et le cinéma, avec deux projets fleuves qui seront entrelacés par Image de Ville : celui de Marc et Christian Barani (Patrimoines : héritage/hérésie – œuvre commanditée en 2012 par Agora, biennale d’architecture, urbanisme et design de Bordeaux.*) et celui de Cédrik Eymenier (Platform).
Le désir de ville du cinéma
Le Festival Image de Ville met à l’honneur chaque année au mois de novembre, d’Aix-en-Provence à Marseille, en passant par Martigues et Port-de-Bouc, le cinéma sur l’architecture et la ville, autour d’une thématique à chaque fois particulière. Son directeur artistique, Luc Joulé, répond ici à nos questions.
Comme le résumait déjà il y a plus de dix ans le sociologue Olivier Mongin dans La condition urbaine, « les flux l’emportent sur les lieux, le privé domine le public et l’entre-soi gagne sur la diversité sociale. » Que peut le cinéma pour contrer cette tendance et continuer à « faire ville » ?
Lorsque, sur une idée de Bruno Jourdan, nous avons lancé le Festival Image de Ville en 2003, nous ressentions le besoin de faire de la question urbaine une question culturelle et de proposer une autre façon de comprendre le statut des images par rapport à la ville et à l’architecture. On assiste aujourd’hui à une saturation de la communication et du marketing qui est le versant « spectaculaire-marchand » de la production, y compris celle de l’espace bâti.
L’enjeu de la culture, c’est d’abord de déconstruire cela, ce réflexe conditionné autour des « images de ville » qui vendent le projet urbain et l’appauvrissent en même temps. Comme le rappelle la philosophe de l’image Marie-José Mondzain, la culture c’est avant tout « la capacité respectée, déployée et sans cesse accrue, offerte à chacun sans distinction, de prendre la parole, de s’approprier sa langue, de construire sa mémoire, mais aussi de décider des figures de l’avenir, de s’emparer de la plasticité du réel pour en faire surgir l’inédit, l’inouï et l’infinité des possibles. »
Bien sûr le cinéma ne peut pas tout et ne peut pas grand chose seul ; mais il est essentiel que sa narration, son rythme, ses élisions aussi, en d’autres termes sa proposition artistique viennent à la rencontre tant du maitre d’ouvrage, du maire que de l’architecte et de l’urbaniste, jusqu’à l’usager. Tout le monde se retrouve devant l’écran de cinéma. Le film est d’autant plus fort qu’il est inséré dans une proposition culturelle plus large. Ainsi, le grand historien de la ville qu’est Marcel Roncayolo vient de faire paraître un nouveau livre sur Marseille. Pour ce géographe qui a consacré des décennies à des « lectures » de villes, qui a donné à comprendre la fabrication de l’espace urbain, sa forme et le devenir de ses héritages, la ville est le lieu de la médiation culturelle, de la rencontre et de l’échange. Cinéphile, il considère le cinéma comme un point de vue essentiel sur la ville qui complète et enrichit la recherche scientifique. Il allait même jusqu’à considérer le cinéaste René Allio comme son “double” lorsqu’il donne à voir Marseille dans ses films, comme La vieille dame indigne ou encore L’heure exquise... Il était donc essentiel pour nous d’accompagner cette parution en apportant une contribution cinématographique à une programmation de conférences et d’itinéraires de randonnées urbaines coordonnée par le Musée d’Histoire de Marseille. Il va de soi qu’il en ressort pour le public un kaléidoscope d’images sur une ville telle que Marseille mais des images qui travaillent autrement que celles de l’acte de marketing.
Quel rapport entretient le cinéma avec l’architecture de nos villes et réciproquement ?
Là où les deux disciplines se retrouvent, c’est dans l’approche de l’espace et du temps, c’est là que se joue leur communauté. Dès L’homme à la caméra de Dziga Vertov (1929), on découvre la ville de manière organique. Il y a déjà cette question du repli invisible, de ce que la caméra donne à voir, prenant une autonomie de composition et de création de l’espace. C’est la magie instituante de l’objet technique qu’est la caméra. Le nouveau réalisme italien ou la Nouvelle vague descend dans la rue et s’oppose à la perfection des décors de studio. Chez Godard, Rivette, Rohmer et bien d’autres, la rue est source de fiction et de vitalité. Dans les Dites cariatides (1984), Agnès Varda donne vie aux décors de façades hausmaniens en les interpellant. La ville a toujours été un objet de fascination et d’inspiration pour le cinéma.
Réciproquement, sans imaginaire, un lieu n’est rien. Un bâtiment comme un territoire. C’est ainsi que nous pouvons l’habiter. Depuis des lieux et des territoires accueillants et hospitaliers, l’architecture nous permet d’habiter le monde. Le cinéma, révélant et transportant les récits inspirés des lieux, peut de la même manière nous permettre de les habiter. Cinéma et architecture nous aident ainsi à habiter le monde. Ils ont ensemble à imaginer de nouveaux lieux et de nouveaux récits.
La ville au cinéma est à la fois notre quotidien et un monde qui reste à faire. C’est pourquoi – à chaque fois qu’on choisit un angle éditorial pour la programmation du Festival Image de Ville, on en revient toujours à la même question – quand on pose la proximité entre cinéma et architecture, le travail du cinéaste et celui de l’architecte, l’enjeu dépasse toujours l’un et l’autre. Car c’est toujours la même question qui revient, celle de ce vivre ensemble urbain. Habiter, vivre, c’est le leitmotiv. Ce n’est pas parce que nous aurions passé ce cap en 2008 de la majorité de l’humanité vivant en ville qu’on sait vivre en ville, qu’il y a une culture de l’habiter urbain. Le cinéma rend visible l’invisible, il montre des choses qu’on ne peut pas forcément saisir, c’est une proposition qui ouvre un espace où les uns et les autres se retrouvent autour d’un objet sensible et poétique. Quand on est assis dans une salle noire, l’émotion est la même pour chaque spectateur. À partir du moment où on propose un film, le temps de la projection est aussi important que le temps de la parole après. On essaie de ne jamais désarticuler ce couple : le film et la parole. Le film réunit des publics et ouvre sur un dialogue, un échange. C’est ça qui nous intéresse.
Quant à cette fabrique des images de ville, vous entendez aussi la perpétuer et y associer les architectes, en les faisant même filmer. Pourquoi rapprocher les architectes des cinéastes ?
Avec le festival et ce qu’il porte, nous ne nous contentons pas de montrer des films. Nous pensons que nous avons également vocation à accompagner des auteurs et des projets cinématographiques depuis leur conception. La position qu’occupe Image de ville, d’observation de la création cinématographique sur l’architecture et la ville, et le réseau de personnalités que les différentes éditions festivalières enrichissent chaque année constituent indéniablement un capital dont nous souhaitons faire profiter des auteurs au moment de l’écriture de leur film.
Depuis 2012, nous faisons même faire des films à des architectes ! Notre idée est de produire une exposition de cinéma sur la ville méditerranéenne. Cette ville existe-t-elle ? Si oui, quel est son “idéal” ? Pour répondre à cette question, nous formons des couples d’architectes et de cinéastes. Chaque couple s’empare d’une thématique propre à la ville méditerranéenne et engage une correspondance, un dialogue. C’est-à-dire que chacun s’adresse à l’autre par l’intermédiaire d’une « lettre-film ». L’aller-retour fonctionne jusqu’à épuisement. L’exposition réunira l’ensemble de ces correspondances et donnera à découvrir une ville méditerranéenne qui n’existe sur aucune carte, mais simplement née de l’imaginaires des cinéastes et des architectes réunis à cette occasion. Nicolas Michelin, architecte, travaille en ce moment avec un cinéaste algérien, Mohamed Lakhdar Tati. Leur sujet est la question de la rue dans la ville méditerranéenne. Un autre couple réunit Marc et Christian Barani. L’un architecte, l’autre cinéaste. Ils mènent une correspondance sur la question de l’horizon dans la ville méditerranéenne.
Grâce au processus de fabrication d’images qu’est le film, on peut envisager des coopérations et des relations qui, malheureusement, demeurent à l’heure actuelle à l’état d’épiphénomènes. Je pense que la pratique cinématographique est un enjeu très fort au niveau de l’enseignement de l’architecture. L’école d’architecture de Paris / La Villette est assez à la pointe sur ce créneau, certains étudiants peuvent même y présenter leur mémoire de fin d’étude sous une forme cinématographique. Dans les métiers de l’architecture, de la ville et du paysage qui produisent et vont produire l’espace urbain, faire acte de cinéma c’est poser un regard sur la ville ou le territoire : comment ce regard documente-t-il le territoire, comment participe-t-il d’une démarche complémentaire et nécessaire à des pratiques d’enseignement, de recherche et d’expérimentation de la ville ? Cela devrait s’institutionnaliser un peu et gagner en diffusion. On voit trop souvent de gros maitres d’ouvrage qui lancent des projets énormes et ne se soucient des apports éventuels de l’art à la fabrique urbaine qu’au travers d’une démarche tardive de communication glorieuse. Alors que c’est au début que l’artiste et le cinéaste ont des choses à nous montrer du territoire d’opération, avec les paysagistes, les sociologues et bien d’autres. C’est au début des transformations de l’aspect de la ville, de sa morphologie, qu’il faut se poser la question des coopérations et des contributions dont est capable à son niveau le cinéma, y compris d’ailleurs dans la capacité à réunir des publics autour d’une image de ville.
Manifeste pour un nouveau répertoire photographique
Comment un territoire gagne-t-il en « plus-value » visuelle ? Est-ce qu’un regard d’auteur peut valoriser et montrer autrement l’ensemble de ses patrimoines matériels et immatériels ? Philippe Guionie, directeur de la Résidence 1+2, a la conviction que oui. Lui-même photographe (représenté par l’agence MYOP et la galerie Polka) et enseignant à l’ETPA, a donné en 2016 le coup d’envoi de la première saison de la « Résidence 1+2 ». Le principe est d’accueillir à Toulouse trois photographes dont un confirmé et deux représentants de la (très) jeune génération. Trois photographes, dont un toulousain et deux autres venant de deux métropoles européennes, Bruxelles ou Barcelone… « Chacun est autonome, insiste Philippe Guionie, mais l’ADN de la Résidence est incarné par le +. À mi-chemin entre résidence de territoires et masterclass, le partage de savoirs est essentiel. Le photographe de renom doit accompagner les deux autres sans les diriger. C’est un jeu subtil à trois, tout en nuances et convictions. » Pour inaugurer cette résidence au format inédit en France, ont donc travaillé ensemble, mais chacune à leur projet respectif, trois photographes : Alice Lévêque (France/Toulouse, 23 ans), la toute jeune Lea Patrix (Belgique, 16 ans) et Diana Lui (Malaisie, 48 ans). Ces trois photographes ont confronté leurs regards d’auteures selon une approche documentaire au sens large du terme, avec des techniques très différentes, du travail à la chambre photographique argentique 20x25 au Polaroïd, en passant par le numérique. Les trois projets ouvrent une collection éditoriale « Toulouse », avec trois livres sous coffret dont la réalisation est confiée aux éditions Filigranes ainsi qu’un film documentaire de 26 minutes racontant le temps de la résidence (deux mois).
Ces œuvres photographiques font l’objet d’une exposition au Musée d’art moderne et contemporain Les Abattoirs à Toulouse (vernissage vendredi 04 novembre à 18h suivi d’un colloque samedi 05 novembre à l’auditorium de ce même lieu). À parcourir les tirages qui sont proposés, on est saisi par la façon dont ces récits expriment de nouvelles intuitions sur le patrimoine toulousain, dans les brassages de cultures, les diasporas, les modes de vie, les mobilités urbaines, l’architecture, la culture scientifique, les collections muséales… À découvrir et à prolonger l’année prochaine, avec des photographes venant de Barcelone… www.1plus2.fr
Alice Lévêque
Née en 1993, Alice Lévêque découvre très tôt la photographie qui s’impose comme le médium de prédilection lui permettant de révéler sa sensibilité construite au fil de ses voyages de jeunesse entre Europe et Afrique. Lauréate du Grand Prix de l’École de Photographie et de Game Design (ETPA) en 2015 à Toulouse, elle est l’un des talents émergents de la photographie française. Sensible à l’univers de la mode, adepte de la couleur et de la lumière continue, Alice dialogue avec les matières, les déséquilibres du corps et le mouvement, autant de thèmes récurrents dans son processus créatif. Ses séries « Petite » et « C’est beau une ville la nuit » sont exposées en 2015 au festival ManifestO. www.aliceleveque.com

Diana Lui
Née en Malaisie en 1968, Diana Lui a vécu avec ses parents jusqu’à l’âge de 14 ans pour vivre ensuite aux États-Unis en raison des problèmes politiques et économiques de son pays natal. Après l’obtention d'une maîtrise en Arts Plastiques à l’Art Center College of Design et d’un master à l’Université de Californie à Los Angeles (UCLA), Diana Lui émigre en Europe, en Belgique puis en France à partir de 1998. Ses œuvres sont présentes dans de nombreuses collections tels que la Bibliothèque Nationale de France à Paris, le Musée des Beaux-Arts à Canton, le Musée de la Photographie à Charleroi, l’University California à Los Angeles… www.99medusas.com

Lea Patrix
Passionnée par la photographie depuis son enfance, Lea Patrix, née en 2000, suit dès l’âge de 13 ans l’enseignement de la photographe Diana Lui, lors de deux workshops successifs aux Rencontres d’Arles, avant de poursuivre son apprentissage en 2015 avec Philippe Guionie. L’urbanité, l’architecture, l’intimité d’un groupe social sont quelques-uns de ses thèmes de prédilection, partie prenante d’une photographie documentaire sensible et protéiforme, portée par un regard d’une grande maturité.

Exposer le patrimoine bâti

Inscrite dans la stratégie nationale pour l’architecture, la Cité de l’architecture et du patrimoine s’adresse à des publics variés, en exposant la qualité architecturale, mettant en scène l’innovation et l’expérimentation tout en soulignant la fragilité du patrimoine. Entretien avec Corinne Bélier, conservatrice générale et directrice du musée des Monuments français.

Viollet-le-Duc s’exprime en 1877 sur les monuments à sélectionner comme « monuments historiques ». En 1879, naît, à son initiative, le musée de Sculpture comparée qui deviendra très vite le musée des Monuments français. Les cours de l’École de Chaillot destinés aux architectes-restaurateurs sont créés en 1887… On a le sentiment d’une urgence à exposer le patrimoine bâti, qui touche tant à l’héritage national, à la diffusion culturelle, qu’aux normes et aux savoirs techniques. D’où vient cette exigence ?
Il faut remonter à la création du poste d’inspecteur des Monuments historiques en 1830, d’abord occupé par Ludovic Vitet puis par Prosper Mérimée (1834), dont on sait qu’il va sillonner la France et entamer le classement des édifices. Puis, en 1837, c’est la naissance de la Commission des Monuments historiques. Viollet-le-Duc dont la carrière est au service de la restauration d’édifices, en sera l’un des membres. Cet acte de reconnaissance du patrimoine bâti, au sens littéral du terme – apprendre à connaître, à classer – débute donc sous la Monarchie de Juillet. Les changements politiques ont été rapides et importants, et les dissensions sont très fortes : il y a eu la Révolution française, puis l’Empire napoléonien. La Monarchie de Juillet tente alors en écrivant le « roman national », de rassembler les français malgré les divergences. Louis Guizot, ministre de Louis Philippe, est un acteur majeur de ce grand récit national. Le XIXe siècle est le siècle où l’on écrit l’histoire nationale et où l’on fonde la notion de patrimoine à partir d’un socle de connaissances en cours de constitution. Ainsi, le musée des Monuments français, d’abord musée de Sculpture comparée, est à la fois issu d’une série de travaux de recherche, d’un méticuleux travail d’identification, mais aussi de l’écriture d’une histoire nationale.
Et l’on va privilégier, il faut le noter, l’histoire médiévale. Des personnalités telles que Mérimée et Viollet-le-Duc vont construire ce choix d’une période qui illustre le mieux, selon eux, l’identité nationale, et notamment l’art et l’architecture gothiques « car nés en Île-de-France ». De façon surprenante, en Angleterre comme en Allemagne, on revendique aussi l’art gothique comme un art « national » par définition. Le musée de Sculpture comparée, décidé par Jules Ferry à la mort de Viollet-le-Duc, est destiné à l’étude et à la diffusion de l’art médiéval, roman et gothique, et, au travers de cet art, c’est un certain génie français qui est glorifié. Sous l’égide de la Commission des Monuments historiques se constituent ses grandes collections de moulages qui restent uniques sur la scène internationale. Par ces moulages de fragments d’édifices, de sculpture monumentale et d’ornementation, on veut tenir un discours didactique et scientifique. À la différence d’autres musées, la collection est complètement choisie : est posée à chaque fois la question de ce qui « mérite » d’être montré, selon un processus de sélection adossé à la politique patrimoniale menée par le Service des monuments historiques depuis sa fondation.
L’histoire de l’art et de l’architecture médiévales, qui commence à s’écrire à cette époque-là, renferme pour les fondateurs du musée un authentique savoir, qu’ils jugent pertinent pour la création architecturale de leur temps. Les collections sont le reflet de cette conviction. Elles illustrent la connaissance que l’on a des édifices, de leurs structures et de leur décor monumental, mais fonctionnent également comme répertoire ou recueil de modèles. Elles apportent un savoir qui n’est pas seulement celui de l’inspecteur, du conservateur ou de l’historien, mais aussi celui de l’architecte. L’architecte-restaurateur doit savoir comment « tiennent » ces monuments et comment les rénover. C’est l’enseignement dispensé à partir de 1887 par ce qui deviendra l’École de Chaillot, toujours partie intégrante de la Cité de l’architecture et du patrimoine. Les grandes maquettes du musée relèvent ainsi de l’analyse structurelle, de la compréhension intime des bâtiments, de leur anatomie. Mais, dans l’esprit de Viollet-le-Duc, la connaissance patrimoniale sert la création contemporaine. Au travers de cette collection, on rassemble un ensemble de modèles structurels ou d’ornementation, non pas à copier, mais dont l’esprit doit pouvoir inspirer les artisans et architectes de son temps afin de créer une architecture nouvelle, propre au XIXe siècle. Viollet-Le-Duc attribue par exemple aux maitres d’œuvre de l’architecture gothique une approche rationaliste qu’il juge nécessaire d’étudier pour inventer l’architecture du temps présent, comme structure et comme art.
Ces moulages de sculpture et ces très grandes maquettes d’analyse structurelle que le musée expose aujourd’hui ont donc une vocation multiple dès le départ : on s’adresse au grand public dont on souhaite l’édification, on constitue un répertoire d’étude de monuments souvent inaccessibles ou éclatés géographiquement sur le territoire français, et l’on s’adresse en même temps aux architectes, artistes et artisans. Le Victoria & Albert Museum de Londres avait lui aussi posé cette ambition de renouvellement du langage des professionnels par ses collections.
En quoi la grande galerie moderne s’inspire-t-elle à son tour de cette vocation multiple ?
Lorsque nous avons conçu la galerie moderne, s’imposait à nous cette histoire d’un musée « didactique », qui avait rassemblé ses collections au bénéfice de son sujet, de sorte qu’on n’expose pas l’architecture elle-même, mais son analyse par la maquette ou le dessin. À cela s’ajoutait inévitablement la notion d’exemplarité des exemples choisis : justement parce qu’il est musée, c’est-à-dire un dispositif de monstration, le musée est toujours confronté à l’exemplarité, d’une manière ou d’une autre. La qualité architecturale, l’innovation et l’expérimentation ont ainsi guidé les choix.
En revanche, de la notion de monument, on est passé à une approche beaucoup plus large de la création et du patrimoine architectural. Depuis les années 1880, la notion de patrimoine s’est d’ailleurs étendue : des cathédrales médiévales on s’est ouvert à d’autres patrimoines, rural, industriel, etc. Les édifices exposés ont ainsi été choisis pour leur valeur d’exemple – à un moment donné, ils ont apporté une réponse remarquable à un programme et un contexte donnés – mais ils figurent aussi le plus souvent déjà dans notre patrimoine national. Toulouse le Mirail par exemple, au sein des grands ensembles, possède incontestablement cette dimension. La labellisation ou le classement en tant que monument historique des architectures du XXe siècle rencontre en partie les choix exposés dans la galerie moderne. Ces édifices ont une valeur patrimoniale reconnue, ils sont des témoins de la création et de l’innovation, tels les ouvrages de Perret, du Corbusier, de Jean Prouvé, ou d’Henri Sauvage (1927). Cette galerie moderne contribue selon nous à la fois à la constitution d’un savoir et d’une culture architecturale, mais aussi d’une mémoire collective, ravivée sans cesse par le fait que nous abordons des questions qui demeurent les nôtres : le logement, les loisirs, le travail, des questions qui sont très présentes dans notre cadre de vie. L’architecture et le patrimoine bâti ne sont pas des objets lointains mais des objets inscrits dans le quotidien des usages et la mémoire collective, la préservation du patrimoine est en conséquence essentielle pour le maintien de notre cadre de vie.
Dans les collections de la Cité entrent aussi les archives d’agences d’architecture (Bernard Zehrfus, Rémi Lopez, Bernard Huet…), avec des documents graphiques, des plans, qui sont une source exceptionnelle pour la recherche, et auxquels on vient aussi se référer lorsqu’on a besoin de repenser les quartiers concernés. Nous travaillons aussi beaucoup sur le rapport de l’architecture contemporaine au patrimoine et avons fait entrer dans les collections par exemple le projet de passerelle de Dietmar Feichtinger au Mont Saint Michel, ou bien le projet de valorisation du site du pont du Gard, confié à Jean-Paul Viguier. Maquettes, plans, photographies de suivi montrent l’évolution du projet, de l’idée de départ à la réalisation.
Le « patrimoine urbain » a-t-il droit de cité à la Cité ? Comment faire accéder le public à une dimension de la ville qui va au-delà des « machines célibataires » (selon l’expression de Le Corbusier) de l’architecture ou bien des grands plans d’urbanisme de survol ?
L’approche patrimoniale elle-même a évolué, de l’édifice nu, on s’est mis à considérer ses abords, puis le tissu urbain lui-même, avec les secteurs sauvegardés et les zones de protection du patrimoine architectural, urbain et paysager (ZPPAUP). On aborde ainsi la cohérence d’un ensemble, une série dont on ne protège pas nécessairement les éléments, mais un caractère qui est particulier à la ville : une cité jardin, un alignement de quais, une cité balnéaire, les grands ensembles, etc. La protection s’est par exemple étendue aux Courtillières (Émile Aillaud, Seine-Saint-Denis) et à la Grande Motte (label XXe siècle). La programmation de la Cité de l’architecture nous permet d’aborder davantage la question de la ville. L’actuelle exposition sur les stations balnéaires appartient totalement à cette démarche. La préoccupation actuelle sur l’avenir des centres anciens recoupe en partie la problématique de la cité balnéaire, où il s’agit de conjuguer l’identité de la ville, le développement touristique et le développement du territoire. Quelle planification du territoire permettrait de gérer au mieux les problématiques naturelles du littoral et les problématiques de développement urbain ? C’est une question d’une actualité. La Cité de l’architecture et du patrimoine espère mettre en perspective ces problématiques, afin de mieux saisir le présent et de projeter le futur.
Corinne Bélier
Conservateur général du patrimoine, Corinne Bélier dirige le Département des collections et le musée des Monuments français à la Cité de l’architecture et du patrimoine (Paris). Elle est à l’origine – au sein d’un commissariat tripartite – de la Galerie d’architecture moderne et contemporaine consacrée à l’architecture française depuis 1851. Elle vient d’inaugurer une exposition sur l’architecture des villes balnéaires, Tous à la plage !

Paris Plage 2
Venant d’ouvrir ses portes, l’exposition temporaire Tous à la plage ! offre le premier panorama cohérent des villes balnéaires en France, fruit d’une trentaine d’années de recherche. Trois séquences sont proposées : « inventer la villégiature », « l’essor des grandes vacances à la mer » et « quelles villes balnéaires demain ? ». Patrimoine bâti et patrimoine naturel y sont abordés. La Grande Motte est en effet aujourd’hui labellisée tout entière patrimoine du XXe siècle. Par leurs ensembles naturels et bâtis sur le littoral, les stations balnéaires sont des unités urbaines en tension, qui attirent les hétérotopies architecturales et dont le développement fut pendant longtemps seulement guidé par l’exploitation touristique. La Cité de l’architecture, qui reçoit une moyenne de 1600 visiteurs par jour sur ses expositions permanentes et temporaires, nous propose donc une saison originale à la plage, jusqu’au 13 février 2017.

Sorti des presses : Des miettes d’étoiles derrière soi
Les Éditions Privat et le Dialogue métropolitain de Toulouse  se sont associés pour concevoir un ouvrage original en accord avec le parti pris de modernité et de contemporanéité qui est celui de la Biennale européenne du patrimoine urbain.
Il s’agit d’un objet étrange. Plutôt qu’un ouvrage strictement documentaire et érudit sur le patrimoine bâti des collectivités du Dialogue métropolitain, il s’agit d’un livre d’histoires croisées. C’est donc un récit composite qui, tant du point de vue textuel qu’iconographique, assume une prise en charge subjective de la mémoire et de l’identité patrimoniale de la région Occitanie. Porté par des auteurs reconnus, Des miettes d’étoiles derrière soi ménage une série de rencontres, réelles, imaginaires ou symboliques entre les villes. Mis en pages en format à l’italienne, illustré avec soin, il entend s’adresser à l’amateur de fictions comme de beaux livres.
Récits, traces, parcours en patrimoine
Des miettes d’étoiles derrière soi offre une narration – parmi beaucoup d’autres possibles – de l’identité urbaine d’un groupement de collectivités se reconnaissant une communauté d’histoire et de destin, le réseau métropolitain de Toulouse, dans le Sud-Ouest de la France. La métropole toulousaine est en effet reliée à des villes moyennes et à leurs territoires respectifs – Albi, Auch, Cahors, Carcassonne, Castres, Mazamet, Montauban, Muret, Rodez, le Sicoval, Saint-Gaudens… Soit donc un grand pays au sein de la région Languedoc-Roussillon-Midi-Pyrénées, un territoire dont les singularités locales sont des richesses qui confinent au charnel pour ses habitants. Ces pluralités d’attachement au lieu, à son quartier ou à son bourg, à sa ville, à sa région, elles n’ont pas davantage vocation à être démontrées qu’à se diluer dans un grand récit d’identité factice. Elles sont. Un patrimoine commun existe donc, bruissant des énergies du quotidien, fort d’un certain nombre de points de repères matériels et immatériels.
Nous vivons dans un vieux pays. Les édifices « indiscutables » qu’il nous faut conserver sont connus et documentés, même si ce qui fait patrimoine pour une nation relève d’une histoire complexe et politique. Il y a des ouvrages de régionalisme et de beaux livres qui leur sont consacrés, et à juste titre. On évite simplement ici le glissement hyperbolique du monument au monumental dont pâtit souvent la notion de patrimoine. Sachons plutôt nous rappeler la leçon de l’historien de l’art Aloïs Riegl qui écrivait en 1903 déjà, que « ce n’est pas leur destination originelle qui confère aux monuments leur signification. C’est nous, sujets modernes, qui la leur attribuons. »
Dans les pages de ce livre trois auteurs, trois voix singulières explorent donc cet attachement patrimonial et le restituent par affleurements discrets. Ils accordent leurs tempéraments et approches dans une partition libre, une forme d’improvisation calculée. Et cela pris ensemble, par les effets aussi de la composition qu’on appelle « livre », produit cette sensation, tantôt doucereuse, tantôt violente, d’un dialogue entretenu avec cette part de nous-même qui dit « je suis d’ici ». Le lien à ce cogito territorial est ténu, parfois bridé, parfois extraverti. Pour l’exprimer, nous avions donc besoin de laisser à chacun de ces trois auteurs sa stratégie d’approche, son intime radicalité.
Mouloud Akkouche développe son talent reconnu de novelliste et multiplie les personnages. Il élude ou dramatise. Il entrelace le roman familial, l’anecdote humoristique, le récit épique d’une traversée régionale. Dans son architecture à emboîtement, d’une clarté palladienne, il ménage ainsi des seuils et des passages d’une ville à l’autre, permettant de lier, de nouer ces identités, ces attachements, ces représentations, ces pratiques de l’espace vécu qui sont caractéristiques de notre territoire.
Accompagnant la fresque de la transmission brossée par Mouloud Akkouche, développant une approche subjective assumée, Ulrich Lebeuf offre à ce livre une iconographie singulière. Est-ce le choix de la technique Polaroïd – désormais au rang des antiquités prisées de l’art photographique –, est-ce le dépouillement des espaces, leur dépeuplement étrange sous l’heure lumineuse d’un soleil impérieux, est-ce l’entrechoquement de la modernité du cadrage froid avec la vitalité surprenante des vieilles pierres ? Il semble qu’Ulrich Lebeuf ait réussi à réinventer dans son équipée automobile en Gascogne et Languedoc l’icône surannée et touchante de la carte postale, pas simplement l’artefact touristique qui met en avant les singularités géographiques et le terroir, mais plus profondément, ce sentiment que la carte postale provoque parfois, celui d’une projection dans un temps que nous n’avons pas connu et qui déclenche toutefois en nous une nostalgie.
Le carnet de cette expédition bienveillante au sein de l’ordinaire que mène pour sa part Raphaële Bertho, témoigne à son tour d’un « art de l’intervalle » comme approche paysagère et sensible. L’agence de voyage choisie est au premier abord incongrue : Instagram, c’est-à-dire la plus populaire des applications numériques de partage de photos. Ici, c’est le hashtag ou le « mot dièse » rassemblant les images d’une communauté numérique qui constitue la première amorce d’un récit à vocation initiatique. Dans la « nouvelle invention du quotidien » portée par les nouvelles technologies et les réseaux sociaux, que devient la signature de nos territoires ? Quelle est leur représentation ? Quelle est la place de l’intime ? Quelle est celle du monumental ?
Trois protocoles d’écriture se chevauchent donc dans ce livre sans s’opposer. Au contraire, parce qu’ils sont justes et ont été au bout de leur démarche, sans préjuger d’un horizon d’attente, ces auteurs parviennent à restituer l’un de ces écheveaux d’histoires qui composent la matière vivante de nos villes. Aussi, tant la patience du texte que l’urgence de l’image, les saillies comme les rêveries des promeneurs solitaires, les ruptures d’itinéraires et la petite musique continue du flux de conscience : tout cela et plus encore nous ouvre la porte d’un récit fragile qui n’a pas la prétention de faire le « tour du sujet », un récit fort parce que ne dissimulant pas justement cette fragilité qui est la nôtre devant nos héritages, réels ou symboliques.
Entrez dans ce territoire à situations multiples qu’est Des miettes d’étoiles derrière soi, avec ses fondus-enchaînés numériques et photographiques, ses lignes de promesse et ses carrefours culturels.
Référence : Mouloud Akkouche, Raphaële Bertho, Ulrich Lebeuf, Des miettes d’étoiles derrière soi, Récits, traces, parcours en patrimoine, Récits/Beau livre, Parution novembre 2016, ISBN : 978-2-7089-2952-4, 192 pages, 22.50 € TTC, Éditions Privat`
